[package]
name = "stupid-mc-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
log = "0.4.26"
env_logger = "0.11.7"
clap = { version = "4.5.32", features = ["derive"] }
serde_json = "1.0.140"
uuid = "1.16.0"
dns-lookup = "2.0.4"